//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace biz.dfch.CS.Tosca.Model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    [System.Xml.Serialization.XmlRootAttribute("documentation", Namespace="http://docs.oasis-open.org/tosca/ns/2011/12", IsNullable=false)]
    public partial class tDocumentation {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRequiredContainerFeature {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string feature;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tInterface {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Operation")]
        public tOperation[] Operation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tOperation : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("InputParameter", IsNullable=false)]
        public tParameter[] InputParameters;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OutputParameter", IsNullable=false)]
        public tParameter[] OutputParameters;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tParameter {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(tBoolean.yes)]
        public tBoolean required;
        
        public tParameter() {
            this.required = tBoolean.yes;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public enum tBoolean {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        no,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tExtensions))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tRelationshipTypeImplementation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tImplementationArtifact))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tNodeTypeImplementation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tCapabilityDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tRequirementDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tOperation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tEntityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tPolicyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tArtifactType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tCapabilityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tRequirementType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tNodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tRelationshipType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tPlan))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tDeploymentArtifact))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tEntityTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tPolicyTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tArtifactTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tRelationshipTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tCapability))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tRequirement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tNodeTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tTopologyTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tPolicy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tServiceTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tExtension))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tDefinitions))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tImport))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentation")]
        public tDocumentation[] documentation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tExtensions : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Extension")]
        public tExtension[] Extension;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tExtension : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string @namespace;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(tBoolean.yes)]
        public tBoolean mustUnderstand;
        
        public tExtension() {
            this.mustUnderstand = tBoolean.yes;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRelationshipTypeImplementation : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
        public tTag[] Tags;
        
        /// <remarks/>
        public tRelationshipTypeImplementationDerivedFrom DerivedFrom;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RequiredContainerFeature", IsNullable=false)]
        public tRequiredContainerFeature[] RequiredContainerFeatures;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ImplementationArtifact", IsNullable=false)]
        public tImplementationArtifactsImplementationArtifact[] ImplementationArtifacts;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string targetNamespace;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName relationshipType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(tBoolean.no)]
        public tBoolean @abstract;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(tBoolean.no)]
        public tBoolean final;
        
        public tRelationshipTypeImplementation() {
            this.@abstract = tBoolean.no;
            this.final = tBoolean.no;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tTag {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRelationshipTypeImplementationDerivedFrom {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName relationshipTypeImplementationRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tImplementationArtifactsImplementationArtifact : tImplementationArtifact {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tImplementationArtifact : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string interfaceName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string operationName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName artifactType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName artifactRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tNodeTypeImplementation : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
        public tTag[] Tags;
        
        /// <remarks/>
        public tNodeTypeImplementationDerivedFrom DerivedFrom;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RequiredContainerFeature", IsNullable=false)]
        public tRequiredContainerFeature[] RequiredContainerFeatures;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ImplementationArtifact", IsNullable=false)]
        public tImplementationArtifactsImplementationArtifact[] ImplementationArtifacts;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DeploymentArtifact", IsNullable=false)]
        public tDeploymentArtifact[] DeploymentArtifacts;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string targetNamespace;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName nodeType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(tBoolean.no)]
        public tBoolean @abstract;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(tBoolean.no)]
        public tBoolean final;
        
        public tNodeTypeImplementation() {
            this.@abstract = tBoolean.no;
            this.final = tBoolean.no;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tNodeTypeImplementationDerivedFrom {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName nodeTypeImplementationRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tDeploymentArtifact : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName artifactType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName artifactRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tCapabilityDefinition : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Constraint", IsNullable=false)]
        public tConstraint[] Constraints;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName capabilityType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int lowerBound;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string upperBound;
        
        public tCapabilityDefinition() {
            this.lowerBound = 1;
            this.upperBound = "1";
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tPropertyConstraint))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tConstraint {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string constraintType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tPropertyConstraint : tConstraint {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string property;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRequirementDefinition : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Constraint", IsNullable=false)]
        public tConstraint[] Constraints;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName requirementType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int lowerBound;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string upperBound;
        
        public tRequirementDefinition() {
            this.lowerBound = 1;
            this.upperBound = "1";
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tPolicyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tArtifactType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tCapabilityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tRequirementType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tNodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tRelationshipType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public abstract partial class tEntityType : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
        public tTag[] Tags;
        
        /// <remarks/>
        public tEntityTypeDerivedFrom DerivedFrom;
        
        /// <remarks/>
        public tEntityTypePropertiesDefinition PropertiesDefinition;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(tBoolean.no)]
        public tBoolean @abstract;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(tBoolean.no)]
        public tBoolean final;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string targetNamespace;
        
        public tEntityType() {
            this.@abstract = tBoolean.no;
            this.final = tBoolean.no;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tEntityTypeDerivedFrom {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName typeRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tEntityTypePropertiesDefinition {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName element;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName type;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tPolicyType : tEntityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("NodeTypeReference", IsNullable=false)]
        public tAppliesToNodeTypeReference[] AppliesTo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string policyLanguage;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tAppliesToNodeTypeReference {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName typeRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tArtifactType : tEntityType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tCapabilityType : tEntityType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRequirementType : tEntityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName requiredCapabilityType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tNodeType : tEntityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RequirementDefinition", IsNullable=false)]
        public tRequirementDefinition[] RequirementDefinitions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CapabilityDefinition", IsNullable=false)]
        public tCapabilityDefinition[] CapabilityDefinitions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("InstanceState", IsNullable=false)]
        public tTopologyElementInstanceStatesInstanceState[] InstanceStates;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Interface", IsNullable=false)]
        public tInterface[] Interfaces;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tTopologyElementInstanceStatesInstanceState {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string state;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRelationshipType : tEntityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("InstanceState", IsNullable=false)]
        public tTopologyElementInstanceStatesInstanceState[] InstanceStates;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Interface", IsNullable=false)]
        public tInterface[] SourceInterfaces;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Interface", IsNullable=false)]
        public tInterface[] TargetInterfaces;
        
        /// <remarks/>
        public tRelationshipTypeValidSource ValidSource;
        
        /// <remarks/>
        public tRelationshipTypeValidTarget ValidTarget;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRelationshipTypeValidSource {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName typeRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRelationshipTypeValidTarget {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName typeRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tPlan : tExtensibleElements {
        
        /// <remarks/>
        public tCondition Precondition;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("InputParameter", IsNullable=false)]
        public tParameter[] InputParameters;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OutputParameter", IsNullable=false)]
        public tParameter[] OutputParameters;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PlanModel", typeof(System.Xml.XmlElement))]
        [System.Xml.Serialization.XmlElementAttribute("PlanModelReference", typeof(tPlanPlanModelReference))]
        public object Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string planType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string planLanguage;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tCondition {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string expressionLanguage;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tPlanPlanModelReference {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string reference;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tPolicyTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tArtifactTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tRelationshipTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tCapability))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tRequirement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tNodeTemplate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public abstract partial class tEntityTemplate : tExtensibleElements {
        
        /// <remarks/>
        public System.Xml.XmlElement Properties;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PropertyConstraint", IsNullable=false)]
        public tPropertyConstraint[] PropertyConstraints;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName type;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tPolicyTemplate : tEntityTemplate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tArtifactTemplate : tEntityTemplate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ArtifactReference", IsNullable=false)]
        public tArtifactReference[] ArtifactReferences;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tArtifactReference {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exclude", typeof(tArtifactReferenceExclude))]
        [System.Xml.Serialization.XmlElementAttribute("Include", typeof(tArtifactReferenceInclude))]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string reference;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tArtifactReferenceExclude {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pattern;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tArtifactReferenceInclude {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pattern;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRelationshipTemplate : tEntityTemplate {
        
        /// <remarks/>
        public tRelationshipTemplateSourceElement SourceElement;
        
        /// <remarks/>
        public tRelationshipTemplateTargetElement TargetElement;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RelationshipConstraint", IsNullable=false)]
        public tRelationshipTemplateRelationshipConstraint[] RelationshipConstraints;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRelationshipTemplateSourceElement {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRelationshipTemplateTargetElement {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRelationshipTemplateRelationshipConstraint {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string constraintType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tCapability : tEntityTemplate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRequirement : tEntityTemplate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tNodeTemplate : tEntityTemplate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Requirement", IsNullable=false)]
        public tRequirement[] Requirements;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Capability", IsNullable=false)]
        public tCapability[] Capabilities;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Policy", IsNullable=false)]
        public tPolicy[] Policies;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DeploymentArtifact", IsNullable=false)]
        public tDeploymentArtifact[] DeploymentArtifacts;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int minInstances;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string maxInstances;
        
        public tNodeTemplate() {
            this.minInstances = 1;
            this.maxInstances = "1";
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tPolicy : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName policyType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName policyRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tTopologyTemplate : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NodeTemplate", typeof(tNodeTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("RelationshipTemplate", typeof(tRelationshipTemplate))]
        public tEntityTemplate[] Items;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tServiceTemplate : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
        public tTag[] Tags;
        
        /// <remarks/>
        public tBoundaryDefinitions BoundaryDefinitions;
        
        /// <remarks/>
        public tTopologyTemplate TopologyTemplate;
        
        /// <remarks/>
        public tPlans Plans;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string targetNamespace;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName substitutableNodeType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tBoundaryDefinitions {
        
        /// <remarks/>
        public tBoundaryDefinitionsProperties Properties;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PropertyConstraint", IsNullable=false)]
        public tPropertyConstraint[] PropertyConstraints;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Requirement", IsNullable=false)]
        public tRequirementRef[] Requirements;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Capability", IsNullable=false)]
        public tCapabilityRef[] Capabilities;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Policy", IsNullable=false)]
        public tPolicy[] Policies;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Interface", IsNullable=false)]
        public tExportedInterface[] Interfaces;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tBoundaryDefinitionsProperties {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PropertyMapping", IsNullable=false)]
        public tPropertyMapping[] PropertyMappings;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tPropertyMapping {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceTemplatePropertyRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string targetObjectRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string targetPropertyRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tRequirementRef {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tCapabilityRef {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tExportedInterface {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Operation")]
        public tExportedOperation[] Operation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tExportedOperation {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NodeOperation", typeof(tExportedOperationNodeOperation))]
        [System.Xml.Serialization.XmlElementAttribute("Plan", typeof(tExportedOperationPlan))]
        [System.Xml.Serialization.XmlElementAttribute("RelationshipOperation", typeof(tExportedOperationRelationshipOperation))]
        public object Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tExportedOperationNodeOperation {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string nodeRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string interfaceName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string operationName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tExportedOperationPlan {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string planRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tExportedOperationRelationshipOperation {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string relationshipRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string interfaceName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string operationName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tPlans {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Plan")]
        public tPlan[] Plan;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string targetNamespace;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tDefinitions : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Extension", IsNullable=false)]
        public tExtension[] Extensions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Import")]
        public tImport[] Import;
        
        /// <remarks/>
        public tDefinitionsTypes Types;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ArtifactTemplate", typeof(tArtifactTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("ArtifactType", typeof(tArtifactType))]
        [System.Xml.Serialization.XmlElementAttribute("CapabilityType", typeof(tCapabilityType))]
        [System.Xml.Serialization.XmlElementAttribute("NodeType", typeof(tNodeType))]
        [System.Xml.Serialization.XmlElementAttribute("NodeTypeImplementation", typeof(tNodeTypeImplementation))]
        [System.Xml.Serialization.XmlElementAttribute("PolicyTemplate", typeof(tPolicyTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("PolicyType", typeof(tPolicyType))]
        [System.Xml.Serialization.XmlElementAttribute("RelationshipType", typeof(tRelationshipType))]
        [System.Xml.Serialization.XmlElementAttribute("RelationshipTypeImplementation", typeof(tRelationshipTypeImplementation))]
        [System.Xml.Serialization.XmlElementAttribute("RequirementType", typeof(tRequirementType))]
        [System.Xml.Serialization.XmlElementAttribute("ServiceTemplate", typeof(tServiceTemplate))]
        public tExtensibleElements[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string targetNamespace;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tImport : tExtensibleElements {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string @namespace;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string importType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    public partial class tDefinitionsTypes {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/tosca/ns/2011/12")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/tosca/ns/2011/12", IsNullable=false)]
    public partial class Definitions : tDefinitions {
    }
}
